### ISSUE TITLE
Unable to override trait property

### ISSUE THREAD

**Issue by ebernie** [SimpleSoftwareIO/simple-cache#2]
The example give to enable cache bursting & modifying TTL from within the case implementing the trait doesn't work. Am I missing something?

**Comment by SimplyCorey** [comment]
Can I see your model please?

Just a quick note -- I haven't finished testing this package yet.  I plan on finishing up testing over the next few days and then releasing 1.0

**Comment by ebernie** [comment]
Here you go.
```PHP
class State extends Model {

    use Cacheable;
    protected $cacheBusting = true;

    protected $table = 'states';

    protected $fillable = [ 'country_id','name'];

    public $timestamps = false;

    public static function register(array $attribute)
    {
        return new static($attribute);
    }

}
```

Gives me the following error. 

> App\State and App\Traits\Cacheable define the same property ($cacheBusting) in the composition of App\State. However, the definition differs and is considered incompatible. Class was composed

I forgot to mention that to test out the code, I copied the individual files into my project instead of installing through composer. Does this make any difference?

**Comment by SimplyCorey** [comment]
Fixed in latest master.
