### ISSUE TITLE
Crash if 'where' query parameter is an array

### ISSUE THREAD

**Issue by ebernie** [SimpleSoftwareIO/simple-cache#3]
```PHP
SomeModel::where(['status' => 'show'])->get();
```

Running the above query will trigger a crash 

> Argument 1 passed to App\Helpers\ModelCache\QueryCacheBuilder::__construct() must be an instance of App\Helpers\ModelCache\QueryCache, instance of Illuminate\Database\MySqlConnection given, called in /Users/ebernie/dev/php/ricebowl/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php on line 1942 and defined

Overriding newQuery in QueryCacheBuilder seems to make it go away.
```PHP
public function newQuery() 
{
    return new static($this->cache, $this->connection, $this->grammar, $this->processor);
}
```

**Comment by SimplyCorey** [comment]
Thanks.  I'll get a fix out for both of these issues tonight.

**Comment by SimplyCorey** [comment]
@ebernie Just finished everything up and pushed out 1.0.0.  Let me know if you have any issues.
